project_id = "wdqdvvsygjgrhmafovjb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.enrichment-coach]
verify_jwt = false

[functions.discover-activities]
verify_jwt = false

[functions.enrichment-coach-enhanced]
verify_jwt = false

[functions.discover-activities-enhanced]
verify_jwt = false